from .tabela_notas_fiscais_por_filial import notas_fiscais_por_filial_filtro
from .tabela_registros_atuais_por_filial import registros_atuais_por_filial_filtro
from .tabela_registros_atuais_por_responsavel_e_filial import registros_atuais_por_responsavel_e_filial_filtro
from .tabela_registros_atuais_por_responsavel import registros_atuais_por_responsavel_filtro
from .tabela_responsaveis_por_filial import responsaveis_por_filial_filtro
from .tabela_todos_registros_por_filial import todos_registros_por_filial_filtro